version: "3"

services:
  redis6379:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./du/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./du/assets:/usr/share/nginx/html
    links:
      - minio
      - web


  minio:
    image: minio/minio
    ports:
      - "9000:9123"

    volumes:
      - ./du/data:/data

  web:
    build: ./server
    working_dir: /home/server
    volumes:
      - ./du/server:/home/server

    ports:
      - "9988:9988"

